Olaglasses/Controllers/GlassessController.cs
using Newtonsoft.Json;
using Olaglasses.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Olaglasses.Controllers
{
    [FilterConfig.NoDirectAccess]
    [FilterConfig.AuthorizeActionFilter]
    public class GlassessController : Controller
    {
        OlaGlassesEntities dbEntity = new OlaGlassesEntities();
        public ActionResult Index(string message)
        {
            ViewBag.message = message;
            List<tblProduct> products = new List<tblProduct>();
            products = dbEntity.tblProducts.Where(x => x.ProductCategory != "Accessory").ToList();
            ViewBag.ProductList = products;
            return View();
        }
        public ActionResult Create(int? id)
        {
            tblProduct product = new tblProduct();
            if (id>0)
            {
                 product = dbEntity.tblProducts.Find(id);

            }
            else
            {
                product.Title = "";
                product.shape = "";
                product.Colour = "";
                product.Material = "";
                product.Brand = "";
                product.Gender = "";
                product.AdditionalInfo = "";
                product.AvailableSize = "";
                product.Price =0;
                product.Cost = 0;
                product.Manufacturer = "";
                product.Model = "";
                product.OrignalCode = "";
                product.Mgf_Code = "";
                product.Rim = "";
                product.Sticker = "";
                product.Feature = "";
                product.ProductCategory = "";
                product.ReleatedTo = 0;
                product.SellinClinic = "";
               
            }
            List<tblProduct> tblProducts = dbEntity.tblProducts.Where(x => x.ProductCategory != "Accessory").ToList();
            ViewBag.ProductList = tblProducts;
            return View(product);
        }
        [HttpPost]
        public ActionResult Create(tblProduct product)
        {

            
            if (product.GlassID>0)
            {
                dbEntity.Entry(product).State = EntityState.Modified;
                dbEntity.SaveChanges();
                return RedirectToAction("Index", new { message = "Record Updated Successfully" });

            }
            else
            {
                dbEntity.tblProducts.Add(product);
                dbEntity.SaveChanges();
                return RedirectToAction("Index", new { message = "Record Added Successfully" });
            }
            
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteData(int? id)
        {
            try
            {

                    tblProduct make = dbEntity.tblProducts.Find(id);
                    if (make != null)
                    {
                        dbEntity.tblProducts.Remove(make);
                        dbEntity.SaveChanges();
                    }
                   
               
                return RedirectToAction("Index" , new { message="Record Deleted Successfully"});
            }
            catch (Exception)
            {

                throw;
            }

        }





        public ActionResult VariationIndex(int id,string message)
        {
            ViewBag.message = message;
            List<tblVariation> variations = new List<tblVariation>();
            variations = dbEntity.tblVariations.Where(x => x.ProductID == id).ToList();
            tblProduct p = dbEntity.tblProducts.Find(id);
            ViewBag.Productname = p.Title;
            ViewBag.GlassID = p.GlassID;
            ViewBag.variationstList = variations;
            return View();
        }
        public ActionResult VariationCreate(int? id, int productid)
        {
            ViewBag.color = dbEntity.tblColors.ToList();
            tblVariation product = new tblVariation();
            if (id > 0)
            {
                product = dbEntity.tblVariations.Find(id);

            }
            else
            {
                var path = "/ProjectImages/Variations/placeholder.jpg";
                product.VariationID = 0;
                product.ColorCode = "";
                product.Color1 = "";
                product.Color2 = "";
                product.size = "";
                product.FrameAWidth = 0;
                product.FrameBHeight = 0;
                product.FrameED = "";
                product.FrameDBBridger = "";
                product.FrameTempleLegs = "";
                product.FrameTotalWidth ="";
                product.MinPDNeg = "";
                product.MinPDPositive = "";
                product.ImagePath = path;
                product.ProductID = productid;


            }

            return View(product);
        }
        [HttpPost]
        public ActionResult VariationCreate(tblVariation product, HttpPostedFileBase Image)
        {

            if (Image != null)
            {
                //var ext = Path.GetExtension(Image.FileName);
               
                var path = Path.Combine(Server.MapPath("/ProjectImages/Variations/"), Image.FileName.Replace(" " ,"_"));
                var path1 = Path.Combine(("/ProjectImages/Variations/"), Image.FileName.Replace(" ", "_"));
                product.ImagePath = path1;
                Image.SaveAs(path);
            }
            if (product.VariationID > 0)
            {
                dbEntity.Entry(product).State = EntityState.Modified;
                dbEntity.SaveChanges();
                return RedirectToAction("VariationIndex", new { id = product.ProductID,  message = "Record Updated Successfully" });

            }
            else
            {
                dbEntity.tblVariations.Add(product);
                dbEntity.SaveChanges();
                return RedirectToAction("VariationIndex", new { id = product.ProductID, message = "Record Added Successfully" });
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult VariationDeleteData(int? id,int Productid)
        {
            try
            {

                tblVariation make = dbEntity.tblVariations.Find(id);
                if (make != null)
                {
                    dbEntity.tblVariations.Remove(make);
                    dbEntity.SaveChanges();
                }


                return RedirectToAction("VariationIndex", new { id=Productid,message = "Record Deleted Successfully" });
            }
            catch (Exception)
            {

                throw;
            }

        }


        public  JsonResult GetCoode(string code,int glassID)
        {
            OlaGlassesEntities dbEntity1 = new OlaGlassesEntities();
            int ret = 0;

            List<tblVariation> variation1 = dbEntity1.tblVariations.ToList();
            tblVariation variation = dbEntity1.tblVariations.Where(x => x.ColorCode == code && x.ProductID == glassID).FirstOrDefault();
            if(variation!=null)
            {
                ret = 1;
            }
            
            return Json(ret,JsonRequestBehavior.AllowGet);
        }
    }
}

Olaglasses/Views/Glassess/Index.cshtml
@using Olaglasses.Models;
@{
    List<tblProduct> products = (List<tblProduct>)ViewBag.ProductList;
}
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}



<div class="row">
    <div class="col-md-5 col-5">
        <div class="breadcrumb-bar">
            <div class="container-fluid">
                <div class="row align-items-center">

                    <h2 class="breadcrumb-title">Glasses</h2>
                    

                </div>
            </div>
        </div>
    </div>
    <div class="col-md-4 col-4"></div>
    <div class="col-md-3 col-3 ">

        <a href="@Url.Action("Create","Glassess")" class="btn btn-secondary float-right" style="background-color:var(--Secondery-color); color:white ;float: right;"><i class="fa fa-plus"></i> Add New Glass</a>

    </div>
</div>
<div class="row">
    <div class="col-sm-12">

        <div class="card">
            <div class="card-body">
                @if (ViewBag.message != null && ViewBag.message != "")
                {
                    <div class="alert alert-success alert-dismissible fade show" role="alert" style="padding-right:0 !important" id="LinkCopy">
                        @ViewBag.message
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                    </div>
                }
                <div class="table-responsive">
                    <table class="table table-hover table-center mb-0" id="GlassesList">
                        <thead>
                            <tr>
                                <th>Title</th>
                                <th>Price</th>
                                <th>Manufacturer</th>
                                <th>MFG Code</th>
                                <th>Gender</th>
                                <th>Type</th>
                                <th>Sticker</th>

                                <th class="text-center">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in products)
                            {
                                <tr>
                                    <td>
                                        <h2 class="table-avatar">
                                            <a href="javascript:void(0);">@item.Title</a>
                                        </h2>
                                    </td>


                                    <td>@item.Price</td>
                                    <td>@item.Manufacturer</td>
                                    <td>@item.Mgf_Code</td>
                                    <td>@item.Gender</td>
                                    <td>
                                        @if (@item.ProductCategory == "Sunglass")
                                        {<span class="badge badge-pill bg-primary inv-badge">@item.ProductCategory</span>}
                                        @if (@item.ProductCategory == "Eyeglass")
                                        {<span class="badge badge-pill bg-success inv-badge">@item.ProductCategory</span>}

                                    </td>
                                    <td>
                                        @if (@item.Sticker == "Hot")
                                        {<span class="badge badge-pill bg-danger inv-badge">@item.Sticker</span>}
                                        @if (@item.Sticker == "New Arrival")
                                        {<span class="badge badge-pill bg-warning inv-badge">@item.Sticker</span>}
                                        @if (@item.Sticker == "Top Seller")
                                        {<span class="badge badge-pill bg-success inv-badge">@item.Sticker</span>}

                                    </td>
                                    <td class="text-right">
                                        <div class="table-action">
                                            <a href="@Url.Action("VariationIndex","Glassess",new { id=@item.GlassID})" target="_blank" class="btn btn-sm bg-warning-light">
                                                <i class="fa fa-list"></i> Variations
                                            </a>
                                            <a href="@Url.Action("Product_Details","Products",new { Productid=@item.GlassID})" target="_blank" class="btn btn-sm bg-info-light">
                                                <i class="far fa-eye"></i> View
                                            </a>

                                            <a href="@Url.Action("Create","Glassess", new { id=@item.GlassID})" class="btn btn-sm bg-success-light">
                                                <i class="fas fa-pen"></i> Edit
                                            </a>
                                            <a href="javascript:void(0)" onclick="DeleteData(@item.GlassID)" class="btn btn-sm bg-danger-light">
                                                <i class="fas fa-trash"></i> Delete
                                            </a>
                                        </div>
                                    </td>

                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


<script src="~/Dashboardassets/assets/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="~/Dashboardassets/assets/plugins/datatables/datatables.min.js"></script>
<script>
    function DeleteData(ID) {
      
        var myModal = $('#delete_post');
        $("#id", myModal).val(ID);
        $("#delete_post").modal('show');
    }
    $(document).ready(function () {
        $('#GlassesList').DataTable({
            searching: true,
            "ordering": false
        });
    });
</script>
<script>

    $(document).ready(function () {
        $(".nav li").removeClass("active");
        $('#glass').addClass('active');

    });
</script>

Olaglasses/Views/Glassess/VariationIndex.cshtml
@using Olaglasses.Models;
@{
    List<tblVariation> products = (List<tblVariation>)ViewBag.variationstList;
}
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}



<div class="row">
    <div class="col-md-5 col-5">
        <div class="breadcrumb-bar">
            <div class="container-fluid">
                <div class="row align-items-center">

                    <h2 class="breadcrumb-title">@ViewBag.Productname Variations</h2>


                </div>
            </div>
        </div>
    </div>
    <div class="col-md-4 col-4"></div>
    <div class="col-md-3 col-3 ">

        <a href="@Url.Action("VariationCreate","Glassess", new { productid=@ViewBag.GlassID})" class="btn btn-secondary float-right" style="background-color:var(--Secondery-color); color:white ;float: right;"><i class="fa fa-plus"></i> Add New Variation</a>

    </div>
</div>
<div class="row">
    <div class="col-sm-12">

        <div class="card">
            <div class="card-body">
                @if (ViewBag.message != null && ViewBag.message != "")
                {
                    <div class="alert alert-success alert-dismissible fade show" role="alert" style="padding-right:0 !important" id="LinkCopy">
                        @ViewBag.message
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                    </div>
                }
                <div class="table-responsive">
                    <table class="table table-hover table-center mb-0" id="GlassesList">
                        <thead>
                            <tr>
                                <th>Color Code</th>
                                
                                <th>Size</th>
                                <th>Frame A Width</th>
                                <th>Frame B Height</th>
                                <th>Frame ED</th>
                                <th>Image</th>
                                <th class="text-center">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in products)
                            {
                            <tr>
                                <td>
                                    <h2 class="table-avatar">
                                        <a href="javascript:void(0);">@item.ColorCode</a>
                                    </h2>
                                </td>


                               
                                <td>@item.size</td>
                                <td>@item.FrameAWidth</td>
                                <td>@item.FrameBHeight</td>
                                <td>@item.FrameED</td>
                                <td><a href="@item.ImagePath" target="_blank">Click to view</a></td>
                                <td class="text-right">
                                    <div class="table-action">


                                        <a href="@Url.Action("VariationCreate","Glassess", new { id=@item.VariationID, productid=@ViewBag.GlassID})" class="btn btn-sm bg-success-light">
                                            <i class="fas fa-pen"></i> Edit
                                        </a>
                                        <a href="javascript:void(0)" onclick="DeleteData(@item.VariationID,@ViewBag.GlassID)" class="btn btn-sm bg-danger-light">
                                            <i class="fas fa-trash"></i> Delete
                                        </a>
                                    </div>
                                </td>

                            </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


<script src="~/Dashboardassets/assets/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="~/Dashboardassets/assets/plugins/datatables/datatables.min.js"></script>
<script>
    function DeleteData(ID,ProdID) {

        var myModal = $('#delete_post_variation');
        $("#id", myModal).val(ID);
        $("#Productid", myModal).val(ProdID);
        $("#delete_post_variation").modal('show');
    }
    $(document).ready(function () {
        $('#GlassesList').DataTable({
            searching: true,
            "ordering": false
        });
    });
</script>
<script>

    $(document).ready(function () {
        $(".nav li").removeClass("active");
        $('#glass').addClass('active');

    });
</script>