Olaglasses/Controllers/AccessorriesController.cs
using Olaglasses.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Olaglasses.Controllers
{
    [FilterConfig.NoDirectAccess]
    [FilterConfig.AuthorizeActionFilter]
    public class AccessorriesController : Controller
    {
        // GET: Accessorries
        OlaGlassesEntities dbEntity = new OlaGlassesEntities();
        public ActionResult Index(string message)
        {
            ViewBag.message = message;
            List<tblProduct> products = new List<tblProduct>();
            products = dbEntity.tblProducts.Where(x => x.ProductCategory == "Accessory").ToList();
            dbEntity.Database.ExecuteSqlCommand("Delete from tblglassPicture where glassID=0");       
            dbEntity.SaveChanges();
            ViewBag.ProductList = products;
            return View();
        }
        public ActionResult Create(int? id)
        {
            tblProduct product = new tblProduct();
            if (id > 0)
            {
                product = dbEntity.tblProducts.Find(id);

                List<tblglassPicture> tblglassPictures = new List<tblglassPicture>();
                tblglassPictures = dbEntity.tblglassPictures.Where(a => a.glassID == id).ToList();
                ViewBag.AccessoryImages = tblglassPictures;

            }
            else
            {
                product.GlassID = 0;
                product.Title = "";
                product.shape = "";
                product.Colour = "";
                product.Material = "";
                product.Brand = "";
                product.Gender = "";
                product.AdditionalInfo = "";
                product.AvailableSize = "";
                product.Price = 0;
                product.Cost = 0;
                product.Manufacturer = "";
                product.Model = "";
                product.OrignalCode = "";
                product.Mgf_Code = "";
                product.Rim = "";
                product.Sticker = "";
                product.Feature = "";
                product.ProductCategory = "";
                product.ReleatedTo = 0;
                product.SellinClinic = "";

            }
            return View(product);
        }
        [HttpPost]
        public ActionResult Create(tblProduct product)
        {
            if (product.Title != null)
            {
                
                product.ProductCategory = "Accessory";
                if (product.GlassID > 0)
                {
                    dbEntity.Entry(product).State = EntityState.Modified;
                    dbEntity.SaveChanges();
                    
                    return RedirectToAction("Index", new { message = "Record Updated Successfully" });

                }
                else
                {
                    dbEntity.tblProducts.Add(product);
                    dbEntity.SaveChanges();
                    int Glassid = product.GlassID;
                    List<tblglassPicture> tblglassPictureList = dbEntity.tblglassPictures.Where(x => x.glassID == 0).ToList();
                    foreach (var tblglassPicture in tblglassPictureList)
                    {
                        tblglassPicture.glassID = Glassid;
                        dbEntity.Entry(tblglassPicture).State = EntityState.Modified;
                        dbEntity.SaveChanges();
                    }
                    return RedirectToAction("Index", new { message = "Record Added Successfully" });
                }
            }
            return RedirectToAction("Create", new { id = 0 }) ;

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteData(int? id)
        {
            try
            {

                tblProduct make = dbEntity.tblProducts.Find(id);
                if (make != null)
                {
                    dbEntity.tblProducts.Remove(make);
                    dbEntity.SaveChanges();
                }


                return RedirectToAction("Index", new { message = "Record Deleted Successfully" });
            }
            catch (Exception)
            {

                throw;
            }

        }


        [HttpPost]

        //Upload Files 
        public ActionResult UploadImages(int? ProductId = 0)
        {
            if (Request.Files.Count > 0)
            {
                try
                {


                    HttpFileCollectionBase files = Request.Files;
                    for (int i = 0; i < files.Count; i++)
                    {
                        HttpPostedFileBase file = files[i];
                        string fname;
                        if (Request.Browser.Browser.ToUpper() == "IE" || Request.Browser.Browser.ToUpper() == "INTERNETEXPLORER")
                        {
                            string[] testfiles = file.FileName.Split(new char[] { '\\' });
                            fname = testfiles[testfiles.Length - 1];
                            fname = file.FileName.Replace(" ","_");
                        }
                        else
                        {
                            fname = file.FileName.Replace(" ", "_");

                        }


                        var FolderPath = Server.MapPath("/ProjectImages/AccessoryImage/");

                        if (!Directory.Exists(FolderPath))
                        {
                            // Try to create the directory.
                            DirectoryInfo di = Directory.CreateDirectory(FolderPath);
                        }
                        FolderPath = "/ProjectImages/AccessoryImage/" + fname;
                        

                        tblglassPicture temp = new tblglassPicture();
                        temp.glassID = ProductId;
                        temp.ImagePath = FolderPath;
                        dbEntity.tblglassPictures.Add(temp);
                        dbEntity.SaveChanges();

                        FolderPath = "/ProjectImages/AccessoryImage/";
                        fname = Path.Combine(Server.MapPath(FolderPath), fname);

                        file.SaveAs(fname);

                    }
                    List<tblglassPicture> TemporaryUploadedFiles = new List<tblglassPicture>();

                    TemporaryUploadedFiles = dbEntity.tblglassPictures.Where(p => p.glassID == ProductId).ToList().ToList();
                    return Json(TemporaryUploadedFiles, JsonRequestBehavior.AllowGet);






                }
                catch (Exception ex)
                {
                    return Json("Error occurred.Error details: " + ex.Message);
                }
            }
            else
            {
                return Json("1");
            }
        }

        public ActionResult DeleteImage(int? VCardid = 0, int? ImageId = 0)
        {

            if (VCardid > 0)
            {
                dbEntity.Database.ExecuteSqlCommand("Delete from tblglassPicture where PictureID=" + ImageId);
                //var ProductImage = db.tblTemplatesImages.Where(a => a.ID == ImageId);
                //db.tblTemplatesImages.Remove(ProductImage);
                dbEntity.SaveChanges();

                List<tblglassPicture> ProductUploadedFiles = new List<tblglassPicture>();

                ProductUploadedFiles = dbEntity.tblglassPictures.Where(p => p.glassID == VCardid).ToList();
                return Json(ProductUploadedFiles, JsonRequestBehavior.AllowGet);
            }


            return Json("", JsonRequestBehavior.AllowGet);


        }
    }
}

Olaglasses/Views/Accessorries/Create.cshtml
@using Olaglasses.Models;
@model Olaglasses.Models.tblProduct
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}
<head>

    <link rel="stylesheet" href="~/Dashboardassets/assets/plugins/dropzone/dropzone.min.css">

    <link rel="stylesheet" href="~/Dashboardassets/assets/plugins/bootstrap-tagsinput/css/bootstrap-tagsinput.css">

    <script src="~/Dashboardassets/assets/js/profile-settings.js"></script>

    <script src="~/Dashboardassets/assets/plugins/dropzone/dropzone.min.js"></script>
</head>
<div class="row">
    <div class="col-md-5 col-5">
        <div class="breadcrumb-bar">
            <div class="container-fluid">
                <div class="row align-items-center">
                    @if (Model.GlassID > 0)
                    {
                        <h2 class="breadcrumb-title">Edit Accessory Info</h2>
                    }
                    else
                    {
                        <h2 class="breadcrumb-title">Add Accessory Info</h2>
                    }

                </div>
            </div>
        </div>
    </div>
</div>



<div class="doc-review review-listing custom-edit-service">


    <!-- Add Blog -->
    <div class="card">
        <div class="card-body">

            <form method="post" action="@Url.Action("Create","Accessorries")">
                <input type="hidden" name="GlassID" id="GlassID" value="@Model.GlassID">

                <div class="service-fields">
                    <div class="row">
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label>Title <span class="text-danger">*</span></label>

                                <input class="form-control" type="text" name="Title" id="Title" value="@Model.Title" required="">
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label>Price ($)<span class="text-danger">*</span></label>
                                <input class="form-control" type="number" name="Price" id="Price" value="@Model.Price" required="">
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label>Cost ($)<span class="text-danger">*</span></label>

                                <input class="form-control" type="number" name="Cost" id="Cost" value="@Model.Cost" required="">
                            </div>
                        </div>
                    </div>

                </div>
                <div class="service-fields">
                    <div class="row">

                        <div class="col-lg-4">
                            <div class="form-group">
                                <label>Manufacturer <span class="text-danger">*</span></label>
                                <input class="form-control" type="text" name="Manufacturer" id="Manufacturer" value="@Model.Manufacturer" required="">
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label>File <span class="text-danger">*</span></label>
                                <input class="form-control" type="file" id="TemplateImages" name="TemplateImages" accept="image/jpeg, image/png, image/gif,">
                                <small class="form-text text-muted">Allowed images: size 191 * 112.</small>
                            </div>
                        </div>
                        <div class="col-lg-4" style="margin-top:3%">
                            <div class="form-group">
                                <button class="btn btn-primary submit-btn" type="submit" name="form_submit" value="submit" >Submit</button>
                                <a href="@Url.Action("Index","Accessorries")"><button class="btn btn-secondary submit-btn" type="button" name="form_submit" value="submit">Cancel</button></a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="service-fields">
                    <div class="upload-wrap" id="Products_Image_Div">
                       
                        @if (ViewBag.AccessoryImages != null)
                        {
                            foreach (var item in ViewBag.AccessoryImages)
                            {
                                <div class="upload-images">
                                    <img src="@item.ImagePath" alt="Upload Image" style="width:100% !important">
                                    <a href="javascript:void(0);" class="btn btn-icon btn-danger btn-sm" onclick="DeleteImage('@item.PictureID')"><i class="far fa-trash-alt"></i></a>
                                </div>

                            }
                        }
                    </div>
                </div>
                <br>
                <div class="submit-section">

                </div>
            </form>
            @*<div class="service-fields">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label>Accessory Images</label>
                            <form action="#" class="dropzone"></form>
                        </div>

                    </div>
                </div>*@
        </div>
    </div>
    <!-- /Add Blog -->

</div>

<script>
    $('#TemplateImages').change(function (e) {

       
        if (window.FormData !== undefined) {

            var fileUpload = $("#TemplateImages").get(0);
            var files = fileUpload.files;

            var fileData = new FormData();
            


            for (var i = 0; i < files.length; i++) {
                fileData.append(files[i].name, files[i]);
            }



            var ProductId = $("#GlassID").val();
            // Adding one more key to FormData object
            fileData.append('ProductId', ProductId);

            $.ajax({
                url: '@Url.Action("UploadImages", "Accessorries")',
                type: "POST",
                contentType: false, // Not to set any content header
                processData: false, // Not to process data
                data: fileData,
                success: function (result) {
                   
                    $("#Products_Image_Div div ").remove();
                    var ImageDiv;

                    if (result != null || result.length > 0) {
                        for (var i = 0; i < result.length; i++) {
                            var img = document.createElement('img');
                            img.src = result[i].ImagePath;

                            ImageDiv = "<div class='upload-images'><img src ='" + img.src + "' style='width: 100% !important' >\ <a href='javascript:void(0);'  class='btn btn-icon btn-danger btn-sm' onclick='DeleteImage(" + result[i].PictureID +")'><i class='far fa-trash-alt'></i></a> </div>";
                            $('#Products_Image_Div').append(ImageDiv);
                        }

                    }

                },
                error: function (err) {
                    /alert(err.statusText);/
                }
            });
        } else {
            alert("FormData is not supported.");
        }
    });
</script>
<script>
    function DeleteImage(ImageId) {

        var productId = $("#GlassID").val();
        var ImageId = ImageId;
      $.ajax({
                url: '@Url.Action("DeleteImage", "Accessorries")',
                type: "POST",
                dataType: 'JSON',
                data: { VCardid: productId, ImageId: ImageId },
                success: function (result) {
                 
                    $("#Products_Image_Div div").remove();
                    var ImageDiv;

                    if (result != null || result.length > 0) {
                        for (var i = 0; i < result.length; i++) {
                            var img = document.createElement('img');
                            img.src = result[i].ImagePath;

                            ImageDiv = "<div class='upload-images' > <img src ='" + img.src + "' style='width: 100% !important'>\ <a href='javascript:void(0);' class='btn btn-icon btn-danger btn-sm' onclick='DeleteImage(" + result[i].PictureID +")'><i class='far fa-trash-alt'></i></a> </div>";
                            $('#Products_Image_Div').append(ImageDiv);
                        }

                    }


                },
                error: function (err) {
                    /alert(err.statusText);/
                }
            });
    }
</script>

<script>

    $(document).ready(function () {
        $(".nav li").removeClass("active");
        $('#accessory').addClass('active');

    });
</script>

Olaglasses/Views/Accessorries/Index.cshtml
@using Olaglasses.Models;
@{
    List<tblProduct> products = (List<tblProduct>)ViewBag.ProductList;
}
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}



<div class="row">
    <div class="col-md-5 col-5">
        <div class="breadcrumb-bar">
            <div class="container-fluid">
                <div class="row align-items-center">

                    <h2 class="breadcrumb-title">Accessories</h2>


                </div>
            </div>
        </div>
    </div>
    <div class="col-md-4 col-4"></div>
    <div class="col-md-3 col-3 ">

        <a href="@Url.Action("Create","Accessorries")" class="btn btn-secondary float-right" style="background-color:var(--Secondery-color); color:white ;float: right;"><i class="fa fa-plus"></i> Add New Accessory</a>

    </div>
</div>
<div class="row">
    <div class="col-sm-12">

        <div class="card">
            <div class="card-body">
                @if (ViewBag.message != null && ViewBag.message != "")
                {
                    <div class="alert alert-success alert-dismissible fade show" role="alert" style="padding-right:0 !important" id="LinkCopy">
                        @ViewBag.message
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                    </div>
                }
                <div class="table-responsive">
                    <table class="table table-hover table-center mb-0" id="GlassesList">
                        <thead>
                            <tr>
                                <th>Title</th>
                                <th>Price</th>
                                <th>Cost</th>
                                <th>Manufacturer</th>
                            

                                <th class="text-center">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in products)
                            {
                            <tr>
                                <td>
                                    <h2 class="table-avatar">
                                        <a href="javascript:void(0);">@item.Title</a>
                                    </h2>
                                </td>


                                <td>@item.Price</td>
                                <td>@item.Cost</td>
                                <td>@item.Manufacturer</td>
                                
                                <td class="text-center">
                                    <div class="table-action">
                                        
                                        <a href="@Url.Action("Product_Details","Products",new { Productid=@item.GlassID})" target="_blank" class="btn btn-sm bg-info-light">
                                            <i class="far fa-eye"></i> View
                                        </a>

                                        <a href="@Url.Action("Create","Accessorries", new { id=@item.GlassID})" class="btn btn-sm bg-success-light">
                                            <i class="fas fa-pen"></i> Edit
                                        </a>
                                        <a href="javascript:void(0)" onclick="DeleteData(@item.GlassID)" class="btn btn-sm bg-danger-light">
                                            <i class="fas fa-trash"></i> Delete
                                        </a>
                                    </div>
                                </td>

                            </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


<script src="~/Dashboardassets/assets/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="~/Dashboardassets/assets/plugins/datatables/datatables.min.js"></script>
<script>
    function DeleteData(ID) {

        var myModal = $('#delete_Accessory');
        $("#id", myModal).val(ID);
        $("#delete_Accessory").modal('show');
    }
    $(document).ready(function () {
        $('#GlassesList').DataTable({
            searching: true,
            "ordering": false
        });
    });
</script>
<script>

    $(document).ready(function () {
        $(".nav li").removeClass("active");
        $('#accessory').addClass('active');

    });
</script>