Olaglasses/Controllers/PaymentProcessController.cs
using Olaglasses.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Olaglasses.Controllers
{
    public class PaymentProcessController : Controller
    {
        OlaGlassesEntities dbEntity = new OlaGlassesEntities();


        [HttpPost]
        public ActionResult Index1(int? id=0,double txtordertotal = 0,double txtdiscountamount=0, double txtsubtotal=0)
        {
           
            List<tblOrder> order = dbEntity.tblOrder.Where(x => x.userID == id).ToList();
            List<tblcart> cart = dbEntity.tblcart.Where(x => x.Userid == id).ToList();
            ViewBag.UserID = cart.FirstOrDefault().Userid;


            double tax = txtsubtotal / 100 * 5;
            ViewBag.GrandAmount = txtordertotal;
            ViewBag.txtdiscountamount = txtdiscountamount;
            ViewBag.txtsubtotal = txtsubtotal;
            ViewBag.OrderList = order;
            ViewBag.tax = tax;
            ViewBag.cart = cart;
            tblcart tblcart;
            foreach (var item in cart)
            {
                tblcart = new tblcart();
                tblcart = dbEntity.tblcart.Find(item.Cartid);
                tblcart.GranTotal = txtordertotal;
                tblcart.Discount = txtdiscountamount;
                tblcart.TaxAmount = tax;

                dbEntity.Entry(tblcart).State = EntityState.Modified;
                dbEntity.SaveChanges();
            }
            return View();
        }
        public ActionResult Checkout(int? id = 0, int OlderID=0)
        {
            tblOrder order = new tblOrder();
            if(OlderID>0)
            {
                 order = dbEntity.tblOrder.Where(x => x.OrderID == OlderID).FirstOrDefault();
            }

            List<tblcart> cart = dbEntity.tblcart.Where(x => x.Userid == id).ToList();
            ViewBag.UserID = cart.FirstOrDefault().Userid;
            ViewBag.GrandAmount = cart.FirstOrDefault().GranTotal;
            
            ViewBag.cart = cart;
            return View(order);
        }
        [HttpPost]
        public ActionResult Checkout(tblOrder order, string IsSame , int? id)
        {
            tblcart cart = dbEntity.tblcart.Where(x => x.Userid == id).FirstOrDefault();
            ViewBag.UserID = cart.Userid;
            ViewBag.GrandAmount = cart.GranTotal;
            return View();
        }
        [HttpPost]
        [Obsolete]
        public ActionResult Index(string cardname, string cardNumber, string expirydate, string CVCNumber, int userID, tblOrder order, string IsSame, string amount = "")
        {

            try
            {
                tblUser user = dbEntity.tblUsers.Find(userID);
                tblSetting sa = dbEntity.tblSettings.Find(3);
                DateTime date = Convert.ToDateTime(expirydate);
                int month = date.Month;
                int year = date.Year;
                Stripe.StripeConfiguration.SetApiKey(sa.StripeID);
                var options1 = new Stripe.TokenCreateOptions
                {
                    Card = new Stripe.TokenCardOptions
                    {

                        Number = cardNumber,
                        ExpMonth = month,
                        ExpYear = year,
                        Cvc = CVCNumber,
                    },
                };



                Stripe.TokenService tokenService = new Stripe.TokenService();

                Stripe.Token token = tokenService.Create(options1);

                Stripe.CustomerCreateOptions customer = new Stripe.CustomerCreateOptions();

                customer.Email = user.UserEmail;

                customer.Source = token.Id;

                var custService = new Stripe.CustomerService();

                Stripe.Customer stpCustomer = custService.Create(customer);
                long amounts = Convert.ToInt64(amount) * 100;

                var options = new Stripe.ChargeCreateOptions
                {

                    Amount = amounts,

                    Currency = "USD",

                    ReceiptEmail = sa.ReceipentEmail,

                    Customer = stpCustomer.Id,

                    Description = Convert.ToString("Payment to Ola Glasses"), //Optional  

                };

                //and Create Method of this object is doing the payment execution.  

                var service = new Stripe.ChargeService();

                Stripe.Charge charge = service.Create(options); // This will do the Payment

                string s = charge.Status;
                if (s != "succeeded")
                {
                    ViewBag.message = "There is a problem in transaction please retry.";
                }

                else
                {
                    tblUserPrescription userPrescription;
                    tblOrderDetails orderDetails;
                    tblOrderPrescription orderPrescription;
                    tblOrder tblOrder = new tblOrder();
                    tblOrder = order;
                    tblOrder.userID = userID;
                    tblOrder.OrderDate = DateTime.Now;
                    tblOrder.UserName = user.Firstname + " " + user.Lastname;
                    tblOrder.UserEmail = user.UserEmail;
                    tblOrder.Status = "Not Started";
                    tblOrder.Total = Convert.ToInt64(amount);
                    tblOrder.UserAddress = user.Address;
                    dbEntity.tblOrder.Add(tblOrder);
                    dbEntity.SaveChanges();

                    int orderID = tblOrder.OrderID;

                    List<tblcart> cart = dbEntity.tblcart.Where(x => x.Userid == userID).ToList();

                    foreach (var item in cart)
                    {
                        double subTotal = 0;
                        orderDetails = new tblOrderDetails();
                        orderDetails.OrderID = orderID;
                        orderDetails.ProductID = item.GlassID;
                        orderDetails.Productname = item.Title;
                        orderDetails.ProductPrice = item.Price.ToString();
                        orderDetails.OrderDate = DateTime.Now;
                        orderDetails.Vision = item.VisionType;
                        orderDetails.LensType = item.LensType;
                        orderDetails.UV_Protection = item.UVProtection;
                        orderDetails.Total = item.TotalAmount.ToString();
                        orderDetails.ProductVariation = item.Variationid;
                        orderDetails.quantity = item.Quantity;
                        orderDetails.TaxAmount = item.TaxAmount;
                        orderDetails.Discount = item.Discount;
                        orderDetails.FrameColor = item.Colour;
                        orderDetails.ProductImage = item.ProductImagePath;
                        orderDetails.ShippingAmount = item.Shippingamount;
                        subTotal = item.TotalAmount;
                        if (item.LensType == "Standard")
                        {
                            subTotal = subTotal + 39;
                        }
                        else if (item.LensType == "Enhanced")
                        {
                            subTotal = subTotal + 49;
                        }
                        if (item.UVProtection == "on")
                        {
                            subTotal = subTotal + 20;
                        }
                        orderDetails.Subtotal = subTotal;

                        dbEntity.tblOrderDetails.Add(orderDetails);
                        dbEntity.SaveChanges();

                        if (item.VisionType != "")
                        {
                            orderPrescription = new tblOrderPrescription();
                            orderPrescription.ProductID = item.GlassID;
                            orderPrescription.OrderID = orderID;
                            orderPrescription.r_sph = item.r_sph;
                            orderPrescription.r_cyl = item.r_cyl;
                            orderPrescription.r_axis = item.r_axis;
                            orderPrescription.r_add = item.r_add;
                            orderPrescription.l_sph = item.l_sph;
                            orderPrescription.l_cyl = item.l_cyl;
                            orderPrescription.l_axis = item.l_axis;
                            orderPrescription.l_add = item.l_add;
                            orderPrescription.lensType = item.VisionType;
                            orderPrescription.quantity = item.Quantity;
                            orderPrescription.Fname = item.Fname;
                            orderPrescription.Lname = item.Lname;
                            orderPrescription.prescription = item.prescription;
                            orderPrescription.prescriptionDate = item.prescriptionDate;
                            orderPrescription.PD = item.PD;
                            orderPrescription.UserID = item.Userid;
                            orderPrescription.PDImage = item.PDImage;
                            orderPrescription.PrescriptionImage = item.PrescriptionImage;
                            dbEntity.tblOrderPrescriptions.Add(orderPrescription);
                            dbEntity.SaveChanges();
                            if (item.prescription == "Yes")
                            {
                                userPrescription = new tblUserPrescription();
                                userPrescription.ProductID = item.GlassID;
                                userPrescription.OrderID = orderID;
                                userPrescription.r_sph = item.r_sph;
                                userPrescription.r_cyl = item.r_cyl;
                                userPrescription.r_axis = item.r_axis;
                                userPrescription.r_add = item.r_add;
                                userPrescription.l_sph = item.l_sph;

Olaglasses/Views/PaymentProcess/Index.cshtml
@using Olaglasses.Models;
@{
    List<tblOrder> orders = (List<tblOrder>)ViewBag.OrderList;
    List<tblcart> cart = (List<tblcart>)ViewBag.cart;
}
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<head>
    <style>
        h4 {
            padding-bottom: 0px !important;
        }

        p {
            padding-bottom: 0px !important;
        }
    </style>
</head>
<section class="products-wishlist-hero-aria">
</section>
<!-- ::::products-hero-aria  end:::::: -->





<section class="user-area">
    <div class="has-bg">
        <div class="has-bg-user-left">
            <img src="assets/img/user-information-left-bg.png" alt="">
        </div>
        <div class="has-bg-user-right">
            <img src="assets/img/user-information-right-bg.png" alt="">
        </div>
    </div>
    <div class="container-fluid custum-pd ">

        <div class="user-bg d-flex justify-content-between flex-wrap">
            <div class="user-item" style="width:60% !important">
                <h2>Previous Orders</h2>
                <a class="shopping-btn" href="@Url.Action("Checkout", "PaymentProcess", new { id = @ViewBag.UserID, OlderID = 0 })">
                    <button style="width:50% !important " type="button" class="confirm-btn">Next</button>
                </a>
                <hr>
                <div class="Cardholder input-area">

                    <!-- <div class="my-cart-section"> -->
                    @foreach (var item in orders)
                    {
                        <div class="row">
                            <div class="col-md">
                                <h4>Billing </h4>
                                <p>
                                    @item.BFname @item.BLname,<br> @item.BAddress, <br>@item.Bcity, @item.BState, <br>@item.BCountry (@item.BPostalCode)
                                    <br>@item.BPhone
                                    <br>@item.BEmail
                                </p>

                            </div>
                            <div class="col-md-4">
                                <h4>Shipping </h4>
                                <p>
                                    @item.SFname @item.SLname,<br> @item.SAddress,<br> @item.Scity, @item.SState,<br> @item.SCountry (@item.SPostalCode)
                                    <br>@item.SPhone
                                    <br>@item.SEmail
                                </p>

                            </div>
                            <div class="col-md-4">
                                <a style="width:50% !important " class="shopping-btn" href="@Url.Action("Checkout", "PaymentProcess", new { id = item.userID, OlderID = item.OrderID })">
                                    <button type="button" class="confirm-btn" onclick="Next()">Use to Fill Data</button>
                                </a>
                            </div>
                        </div>
                        <hr>
                    }
                </div>
            </div>
            <div class="user-order-item">
                <h4>Order Summary</h4>
                <div class="frame">
                    @{ double subtotal=0;}
                    @foreach (var item in cart)
                    {
                        <ul>
                            <li>@item.Title X @item.Quantity</li>
                            <li>$@item.TotalAmount</li>
                        </ul>
                        if (item.LensType != null)
                        {
                            <ul>
                                <li>@item.LensType</li>
                                @if (item.LensType == "Standard")
                                {
                                    <li>$@item.39</li>
                                }

                                @if (item.LensType == "Enhanced")
                                {
                                    <li>$@item.49</li>
                                }
                            </ul>
                        }
                        if (item.UVProtection == "on")
                        {
                            <ul>
                                <li>UV Protection</li>
                                <li>$20</li>
                            </ul>
                        }
                        subtotal = subtotal + item.TotalAmount;
                    }
                </div>
                @foreach (var item in cart)
                {
                    <div class="Subtotal">
                        <ul class="active">
                            <li c>Subtotal</li>
                            <li>$@subtotal</li>
                        </ul>
                        <ul>
                            <li>Shipping</li>
                            <li>$9.00</li>
                        </ul>
                        <ul>
                            <li>Discount</li>
                            <li>$@item.Discount</li>
                        </ul>
                        <ul>
                            <li>tax</li>
                            <li>$@item.TaxAmount</li>
                        </ul>
                    </div>
                    <div class="total-order">
                        <h6>order Total</h6>
                        <h6>$@item.GranTotal</h6>
                    </div>
                }
                </div>
        </div>
    </div>
</section>

Olaglasses/Views/PaymentProcess/Index1.cshtml
@using Olaglasses.Models;
@{
    List<tblOrder> orders = (List<tblOrder>)ViewBag.OrderList;
    List<tblcart> cart = (List<tblcart>)ViewBag.cart;
}
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<head>
    <style>
        h4 {
            padding-bottom: 0px !important;
        }

        p {
            padding-bottom: 0px !important;
        }
    </style>
</head>
<section class="products-wishlist-hero-aria">
</section>
<!-- ::::products-hero-aria  end:::::: -->





<section class="user-area">
    <div class="has-bg">
        <div class="has-bg-user-left">
            <img src="assets/img/user-information-left-bg.png" alt="">
        </div>
        <div class="has-bg-user-right">
            <img src="assets/img/user-information-right-bg.png" alt="">
        </div>
    </div>
    <div class="container-fluid custum-pd ">

        <div class="user-bg d-flex justify-content-between flex-wrap">
            <div class="user-item" style="width:60% !important">
                <h2>Previous Orders</h2>
                <a class="shopping-btn" href="@Url.Action("Checkout", "PaymentProcess", new { id = @ViewBag.UserID, OlderID = 0 })">
                    <button style="width:50% !important " type="button" class="confirm-btn">Next</button>
                </a>
                <hr>
                <div class="Cardholder input-area">

                    <!-- <div class="my-cart-section"> -->
                    @foreach (var item in orders)
                    {
                        <div class="row">
                            <div class="col-md">
                                <h4>Billing </h4>
                                <p>
                                    @item.BFname @item.BLname,<br> @item.BAddress, <br>@item.Bcity, @item.BState, <br>@item.BCountry (@item.BPostalCode)
                                    <br>@item.BPhone
                                    <br>@item.BEmail
                                </p>

                            </div>
                            <div class="col-md-4">
                                <h4>Shipping </h4>
                                <p>
                                    @item.SFname @item.SLname,<br> @item.SAddress,<br> @item.Scity, @item.SState,<br> @item.SCountry (@item.SPostalCode)
                                    <br>@item.SPhone
                                    <br>@item.SEmail
                                </p>

                            </div>
                            <div class="col-md-4">
                                <a style="width:50% !important " class="shopping-btn" href="@Url.Action("Checkout", "PaymentProcess", new { id = item.userID, OlderID = item.OrderID })">
                                    <button type="button" class="confirm-btn" onclick="Next()">Use to Fill Data</button>
                                </a>
                            </div>
                        </div>
                        <hr>
                    }
                </div>
            </div>
            <div class="user-order-item">
                <h4>Order Summary</h4>
                <div class="frame">
                    @{ double subtotal = 0;}
                    @foreach (var item in cart)
                    {
                        <ul>
                            <li>@item.Title X @item.Quantity</li>
                            <li>$@item.TotalAmount</li>
                        </ul>
                        if (item.LensType != null)
                        {
                            <ul>
                                <li>@item.LensType</li>
                                @if (item.LensType == "Standard")
                                {
                                    <li>$@item.39</li>
                                }

                                @if (item.LensType == "Enhanced")
                                {
                                    <li>$@item.49</li>
                                }
                            </ul>
                        }
                        if (item.UVProtection == "on")
                        {
                            <ul>
                                <li>UV Protection</li>
                                <li>$20</li>
                            </ul>
                        }
                        subtotal = subtotal + item.TotalAmount;
                    }
                </div>
                   <div class="Subtotal">
                        <ul class="active">
                            <li>Subtotal</li>
                            <li>$@subtotal</li>
                        </ul>
                        <ul>
                            <li>Shipping</li>
                            <li>$9.00</li>
                        </ul>
                        <ul>
                            <li>Discount</li>
                            <li>$@ViewBag.txtdiscountamount</li>
                        </ul>
                        <ul>
                            <li>tax</li>
                            <li>$@ViewBag.tax</li>
                        </ul>
                    </div>
                    <div class="total-order">
                        <h6>order Total</h6>
                        <h6>$@ViewBag.GrandAmount</h6>
                    </div>
                
            </div>
        </div>
    </div>
</section>